media:
  input: public/images
  output: /images

content:
  - name: blog
    label: نوشته‌ها
    type: collection
    path: src/data/post
    format: yaml-frontmatter
    fields:
      - name: title
        label: عنوان
        type: string
        required: true
      - name: publishDate
        label: تاریخ انتشار
        type: date
        default: now
        required: true
      - name: author
        label: نویسنده
        type: string
        default: علی کواری
      - name: category_help
        label: "💡"
        type: text
        default: "physics → فیزیک | chemistry → شیمی | biology → زیست‌شناسی | earth-astronomy → زمین و نجوم | computer-science → علوم کامپیوتر | metaphysics → علوم فرامادی"
      - name: category
        label: "دسته‌بندی (یکی از موارد بالا را اینجا بچسبانید)"
        type: string
        default: biology
      - name: image
        label: تصویر شاخص
        type: image
      - name: excerpt
        label: خلاصه
        type: text
      - name: tags
        label: برچسب‌ها (با ویرگول انگلیسی جدا کنید)
        type: string
        required: false
        default: ""
      - name: body
        label: متن
        type: markdown
