backend:
  name: github
  repo: alikavari2/MySite
  branch: main
  base_url: https://alikavari.ir
  auth_endpoint: /auth/github

local_backend: false

media_folder: public/images
public_folder: /images

collections:
  - name: "posts"
    label: "پست‌ها"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - { label: "متن", name: "body", widget: "markdown" }
