site:
  name: 'سایت شخصی علی کواری'
  site: 'https://alikavari.ir'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: false

metadata:
  title:
    default: 'سایت شخصی علی کواری'
    template: '%s — علی کواری'
  description: 'آزمایشگاه دیجیتال علوم تجربی، فیزیک، شیمی، زیست، نجوم و رایانه'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'سایت شخصی علی کواری'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: fa
  textDirection: rtl

apps:
  blog:
    isEnabled: true
    postsPerPage: 6
    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true
    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true
    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true
    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false
    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark'
